//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesoes()
        {
            this.Tratamento = new HashSet<Tratamento>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataLesao { get; set; }
        public string Diagnostico { get; set; }
        public int IdLocalLesao { get; set; }
        public int IdLadoLesao { get; set; }
        public int IdTipoLesao { get; set; }
        public int IdGravidade { get; set; }
        public int IdOcorrencia { get; set; }
        public int IdAtleta { get; set; }
    
        public virtual Atleta Atleta { get; set; }
        public virtual Gravidade Gravidade { get; set; }
        public virtual LadoLesao LadoLesao { get; set; }
        public virtual LocalLesao LocalLesao { get; set; }
        public virtual Ocorrencia Ocorrencia { get; set; }
        public virtual TipoLesao TipoLesao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamento> Tratamento { get; set; }
    }
}
