//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamento_TipoTratamento
    {
        public int Id { get; set; }
        public int IdTratamento { get; set; }
        public int IdTipoTratamento { get; set; }
    
        public virtual TiposTratamento TiposTratamento { get; set; }
        public virtual Tratamento Tratamento { get; set; }
    }
}
